name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: 546644620269.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: portfolio
          AWS_REGION: us-east-1
        run: |
          docker build -t portfolio .
          docker tag portfolio:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update ECS Task Definition and Service
        env:
          ECS_CLUSTER: portfolio-ecs
          ECS_SERVICE: portfolio-svc
          ECS_TASK_FAMILY: pipeline-portfolio-ecs
          AWS_REGION: us-east-1
        run: |
          latest_revision=$(aws ecs describe-task-definition --region $AWS_REGION --task-definition $ECS_TASK_FAMILY --query 'taskDefinition.revision')
          aws ecs update-service --region $AWS_REGION --cluster $ECS_CLUSTER --service $ECS_SERVICE --task-definition "$ECS_TASK_FAMILY:$latest_revision"
