name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker buildx build -t dvpslklarc/portfolio -f Dockerfile --platform linux/amd64,linux/arm64 .

      - name: Push Docker Image
        run: docker push dvpslklarc/portfolio

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          tf_version: "1.0.6"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Kubernetes Deployment
        run: kubectl apply -f kubernetes-manifests/deployment.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
