name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: 546644620269.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: portfolio
          AWS_REGION: us-east-1
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t $IMAGE_URI:latest -f ./Dockerfile .
          docker tag $IMAGE_URI:latest $IMAGE_URI:$GITHUB_SHA
          docker push $IMAGE_URI:latest
          docker push $IMAGE_URI:$GITHUB_SHA
